services:
  frontend:
    build: frontend
    ports:
      - "8080:80"

  backend:
    build: backend
    ports:
      - "8081:80"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    secrets:
      - tidal_api_key

  redis:
    image: redis
    volumes:
      - redis_data:/data
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

volumes:
  redis_data:

secrets:
  tidal_api_key:
    file: tidal_api_key