#!/usr/bin/env python
import argparse
import logging
import os
import subprocess

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)


def run_tests(service: str, type_: str, extra: list[str]):
    logger.info(f"Running {service} {type_} tests....")
    logger.info("Cleaning up existing services...")
    subprocess.run(["docker", "compose", "down", "--volumes"], check=True)

    compose_files = ["-f", "compose.yaml", "-f", f"compose.test.{service}.{type_}.yaml"]

    logger.info(f"Building images...")
    subprocess.run(["docker", "compose", *compose_files, "build"], check=True)

    cmd = [
        "docker", "compose",
        *compose_files,
        "up", "--abort-on-container-exit", "--renew-anon-volumes",
        "--exit-code-from", service
    ]
    logger.info(f"Running '{" ".join(cmd)}'...")
    extra_joined = " ".join(extra)
    result = subprocess.run(
        cmd,
        env={**os.environ, "TEST_ARGS": extra_joined},
    )
    if not result.returncode:
        logger.info(f"{type_} tests for {service} passed.")
    else:
        raise RuntimeError(f"{type_} tests for {service} failed!")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run tests for tides app.")
    parser.add_argument("SERVICE", type=str, choices=("backend",))
    parser.add_argument("TYPE", type=str, choices=("integration",))
    parser.add_argument("EXTRA", nargs=argparse.REMAINDER)
    args = parser.parse_args()
    extra = args.EXTRA
    if extra and extra[0] == "--":
        extra = extra[1:]
    run_tests(args.SERVICE, args.TYPE, extra)
